version: '3.8'

services:
  cratedb:
    image: crate:5.4.4
    container_name: cratedb
    ports:
      - "4200:4200"  # CrateDB Admin UI
      - "5432:5432"  # PostgreSQL protocol
    environment:
      - CRATE_HEAP_SIZE=1g
    command: >
      crate
      -Cdiscovery.type=single-node
      -Cnetwork.host=_site_
      -Chttp.cors.enabled=true
      -Chttp.cors.allow-origin="*"
    volumes:
      - crate_data:/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - cratedb

volumes:
  crate_data:
  grafana_data: