apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    url: cratedb:5432
    database: crate
    user: crate
    secureJsonData:
      password: ''
    jsonData:
      sslmode: disable
      postgresVersion: 1000
      timescaledb: false
    isDefault: true
    editable: true